version: 3

tasks:
  default: task --list

  install:
    desc: installs dependencies
    cmds:
      - ansible-galaxy install --ignore-errors -r ansible/requirements.yml
    # NOT USED
      # - pip install -r ansible/pip_requirements.txt --no-cache-dir
      # - pipx runpip ansible install -r ansible/pip_requirements.txt --no-cache-dir

  check-inv:
    desc: check proxmox inventory
    aliases:
      - inv
    dir: ansible
    cmds:
      - 'ansible-inventory -i ./inventory --graph --vars {{ .ANSIBLE_HOST }}'

# https://docs.ansible.com/ansible/latest/playbook_guide/playbooks_vars_facts.html
  hostvars:
    desc: print hostvars for ANSIBLE_HOST
    dir: ansible
    cmds:
      - ansible -i ./inventory -m ansible.builtin.setup {{ .ANSIBLE_HOST }} | tee hostvars | less

  ping:
    desc: ping host
    dir: ansible
    cmds:
      - ansible all -i ./inventory -m ping -l {{ .ANSIBLE_HOST }}
