#!/usr/bin/env bash

# https://github.com/willhallonline/docker-ansible

image_version=2.10-alpine-3.13

docker run --rm -it \
-v $(pwd):/ansible \
-v ~/.ssh/github_akijowski_mbp13:/root/.ssh/github_akijowski_mbp13 \
-v ~/.ssh/known_hosts:/root/.ssh/known_hosts \
willhallonline/ansible:${image_version} \
/bin/sh

#
# mkdir -p ~/.ssh && \
# touch ~/.ssh/known_hosts && \
# echo -e "Adding 192.168.11.6 to known_hosts" && \
# ssh-keyscan -H 192.168.11.6 >> ~/.ssh/known_hosts

#ansible-playbook samba/01_initialize.yml -i hosts -l samba -u adam --private-key /root/.ssh/github_akijowski_mbp13 -K

# ansible-galaxy install -r requirements.yml
