version: 3

includes:
  plex:
    taskfile: plex.taskfile.yaml
  ansible:
    taskfile: ansible.Taskfile.yaml
    aliases:
      - a
  k8s:
    taskfile: k8s.Taskfile.yaml
    aliases:
      - k

silent: true

tasks:
  default: task --list
