version: 3

includes:
  ansible:
    taskfile: ansible.Taskfile.yaml
    aliases:
      - a
  k8s:
    taskfile: k8s.Taskfile.yaml
    aliases:
      - k

silent: true

tasks:
  default: task --list

  devcontainer:postcreate:
    desc: postCreate commands for dev container
    cmds:
      - pipx install --include-deps ansible
      - ./bin/direnv_setup
      - ./bin/packer_install

  terminal:
    desc: open a terminal in the dev container
    aliases:
      - shell
      - sh
      - zsh
    cmds:
      - docker exec -it -w /workspaces/home-server -u vscode home_server_devcontainer /usr/bin/zsh

  ssh:key:rm:
    desc: Remove local ssh key hashs, use IVP4 variable
    aliases:
      - ssh:rm
    cmds:
      - 'ssh-keygen -R {{ .IPV4 }}'

  ssh:packer:
    desc: Create an ssh key pair for Packer use. Packer scripts remove this key from the templates after use.
    cmds:
      - |
        ssh-keygen \
        -o \
        -a 100 \
        -t ed25519 \
        -f ~/.ssh/packer_id_ed25519 \
        -C "Packer"
    status:
      - test -f ~/.ssh/packer_id_ed25519

  ssh:packer:rm:
    desc: Remove SSH key pair generated for Packer
    cmds:
      - rm -f ~/.ssh/packer_id_ed25519
      - rm -f ~/.ssh/packer_id_ed25519.pub
