version: 3

includes:
  ansible:
    taskfile: ansible.Taskfile.yaml
    aliases:
      - a
  k8s:
    taskfile: k8s.Taskfile.yaml
    aliases:
      - k

silent: true

tasks:
  default: task --list

  devcontainer:postcreate:
    desc: postCreate commands for dev container
    cmds:
      - pipx install --include-deps ansible
      - ./bin/direnv_setup

  terminal:
    desc: open a terminal in the dev container
    aliases:
      - shell
      - sh
      - zsh
    cmds:
      - docker exec -it -w /workspaces/home-server -u vscode home_server_devcontainer /usr/bin/zsh

  ssh:key:rm:
    desc: Remove local ssh key hashs, use IVP4 variable
    aliases:
      - ssh:rm
    cmds:
      - 'ssh-keygen -R {{ .IPV4 }}'
