---
- hosts: all
  name: Configure Proxmox node
  become: true
  vars_files:
    - vars/proxmox.yml

  tasks:
    - name: Install Prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

    - name: Install sudo
      apt:
        name: sudo
        state: latest

  # Sudo group setup
    - name: Make sure there is a `wheel` group
      group:
        name: wheel
        state: present
    
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
 
  # User and SSH setup
    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ create_user }}"
        state: present
        groups: wheel
        append: true
        create_home: true
        shell: /bin/bash

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ create_user_key }}"

    # - name: Disable password authentication for root
    #   lineinfile:
    #     path: /etc/ssh/sshd_config
    #     state: present
    #     regexp: '^#?PermitRootLogin'
    #     line: 'PermitRootLogin prohibit-password'

  # Install packages
    - name: Update apt
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install required system packages
      apt:
        name: "{{ sys_packages }}"
        state: latest

  # Unattended Upgrades
    - name: Unattended Upgrades
      import_role:
        name: jnv.unattended-upgrades
      vars:
        unattended_automatic_reboot: true
        unattended_syslog_enable: true
        unattended_mail: 'agkijow@gmail.com'
        unattended_mail_only_on_error: true
        unattended_origins_patterns:
          - 'origin=Debian,codename=${distro_codename}-security'
          - 'origin=Debian,codename=${distro_codename}-updates'
          - 'origin=Proxmox,archive=stable,component=pve-no-subscription,site=download.proxmox.com'
