---
- hosts: all
  name: Configure Proxmox users and groups
  become: true
  vars_files:
    - vars/proxmox.yml

  tasks:
    - name: Install Prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

    - name: Add Groups
      group:
        name: "{{ item.name }}"
        gid: "{{ item.gid }}"
        state: present
      loop: "{{ sys_groups }}"

    - name: Add Users
      user:
        name: "{{ item.name }}"
        uid: "{{ item.uid }}"
        group: "{{ item.group }}"
        create_home: "{{ item.create_home }}"
        state: present
      loop: "{{ sys_users }}"