---
- hosts: all
  name: Configure Sanoid for ZFS snapshots
  become: true
  vars_files:
    - vars/proxmox.yml

  tasks:
    - name: Update apt
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install Sanoid Prerequisites
      apt:
        name:
          - debhelper
          - libcapture-tiny-perl
          - libconfig-inifiles-perl
          - pv
          - lzop
          - mbuffer
          - build-essential
        state: latest

    - name: Clone Sanoid
      git:
        repo: https://github.com/jimsalterjrs/sanoid.git
        dest: code/sanoid
        version: v2.1.0

    - name: Message
      debug:
        msg:
          < Sanoid has been cloned from git into the code/sanoid directory
            Follow the instructions at
            https://github.com/jimsalterjrs/sanoid/blob/master/INSTALL.md#debianubuntu
            to complete installation.

    - name: Create Sanoid Directory
      file:
        path: /etc/sanoid
        state: directory
        owner: root
        group: root

    - name: Copy Sanoid Config
      copy:
        src: conf/sanoid.conf
        dest: /etc/sanoid/sanoid.conf
        group: root
        owner: root
        mode: '0660'
