---
- hosts: all
  name: Configure Plex LXC
  become: true
  vars_files:
    - vars/plex.yml
  vars_prompt:
    - name: create_user_password
      prompt: "Enter the password to be used for {{ create_user }}"
      encrypt: sha512_crypt
      confirm: yes

  tasks:
    - name: Install Prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

    - name: Install sudo
      apt:
        name: sudo
        state: latest

  # Sudo group setup
    - name: Make sure there is a `wheel` group
      group:
        name: wheel
        state: present
    
    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'
 
  # User and SSH setup
    - name: Create a new regular user with sudo privileges
      user:
        name: "{{ create_user }}"
        state: present
        groups: wheel
        append: true
        create_home: true
        shell: /bin/bash

    - name: Set authorized key for remote user
      authorized_key:
        user: "{{ create_user }}"
        state: present
        key: "{{ create_user_key }}"

  # Install packages
    - name: Update apt
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install required system packages
      apt:
        name: "{{ sys_packages }}"
        state: latest

  # UFW Setup
    - name: UFW - Allow SSH connections
      ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Deny all other incoming traffic by default
      ufw:
        state: enabled
        policy: deny
        direction: incoming
