---
- hosts: all
  name: Configure Plex LXC
  become: true

  tasks:
  # Install Plex
    - name: Install Plex Repo GPG key
      apt_key:
        url: https://downloads.plex.tv/plex-keys/PlexSign.key
        state: present

    - name: Add Plex Repo
      apt_repository:
        repo: 'deb https://downloads.plex.tv/repo/deb public main'
        state: present
        filename: plexmediaserver

    - name: Update apt
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day

    - name: Install Plex
      apt:
        name: plexmediaserver
        state: latest

  # Configure UFW for Plex
    - name: Copy Plex UFW config
      copy:
        src: conf/ufw-plexmediaserver
        dest: /etc/ufw/applications.d/plexmediaserver
        group: root
        owner: root
        mode: 0660

    - name: Update UFW
      ufw:
        state: reloaded

    - name: Add Plex to UFW
      ufw:
        rule: allow
        name: plexmediaserver-all