---
- hosts: all
  become: true
  vars_files:
    - vars/microk8s.yml

#
# In order to run microk8s effectively, the server is run on a VM
# Therefore the user accounts are set up during vm setup
#
  tasks:
    - name: Install Prerequisites
      apt: name=aptitude update_cache=yes state=latest force_apt_get=yes

  # Sudo group setup
    - name: Make sure there is a `wheel` group
      group:
        name: wheel
        state: present

    - name: Allow 'wheel' group to have passwordless sudo
      lineinfile:
        path: /etc/sudoers
        state: present
        regexp: '^%wheel'
        line: '%wheel ALL=(ALL) NOPASSWD: ALL'
        validate: '/usr/sbin/visudo -cf %s'

  # Install packages
    - name: Update apt (async)
      apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400 #One day
      async: 1000
      poll: 0
      register: apt_sleeper

    - name: Poll for apt update to complete
      async_status:
        jid: "{{ apt_sleeper.ansible_job_id }}"
      register: job_result
      until: job_result.finished
      retries: 30
      delay: 10

    - name: Install required system packages
      apt:
        name: "{{ sys_packages }}"
        state: latest

  # UFW Setup
    - name: UFW - Allow SSH connections
      community.general.ufw:
        rule: allow
        name: OpenSSH

    - name: UFW - Deny all other incoming traffic by default
      community.general.ufw:
        state: enabled
        policy: deny
        direction: incoming

  # Unattended Upgrades
    - name: Unattended Upgrades
      import_role:
        name: jnv.unattended-upgrades
      vars:
        unattended_syslog_enable: true
        unattended_mail: 'agkijow@gmail.com'
        unattended_mail_only_on_error: true
